# Generated by Django 3.1.7 on 2021-04-07 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OriginalData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregnency', models.IntegerField(blank=True, default=0, null=True)),
                ('bmi', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peeatnight', models.BooleanField()),
                ('peelevel', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=100)),
                ('thirstylevel', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=100)),
                ('feeltired', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=100)),
                ('blurryvision', models.BooleanField()),
                ('healing', models.CharField(choices=[('Slow', 'Slow'), ('Fast', 'Fast')], max_length=100)),
                ('hungrylevel', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=100)),
                ('skin', models.BooleanField()),
                ('height', models.FloatField(default=0)),
                ('weight', models.FloatField(default=0)),
                ('age', models.IntegerField(default=0)),
                ('noofpregnency', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
